eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: subject
  application:
    name: lab-4-subject
words: I,You,He,She,It
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: verb
  application:
    name: lab-4-verb
words: ran,knew,had,saw,bought
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: article
  application:
    name: lab-4-article
words: a,the
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: adjective
  application:
    name: lab-4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: noun
  application:
    name: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: ${PORT:${SERVER_PORT:0}}
